### ISSUE TITLE
Parking brake cannot be set

### ISSUE THREAD

**Issue by RGaming007** [YesAviation/747-400#28]
sometimes the parking brake does not set and is forced to the off position

**Comment by mSparks43** [comment]
fcomm says

PARKING BRAKE .............................................................................Set
Verify that the PARK BRAKE SET message shows.
Note: Do not assume that the parking brake will prevent airplane
movement. Accumulator pressure can be insufficient.

1
 Parking Brake Lever
Pull - sets parking brake when both brake pedals simultaneously depressed.
Releases when both brake pedals simultaneously depressed.

Alternate Brake Hydraulic System
If hydraulic system 4 pressure is low, hydraulic system 1 supplies pressure to the
alternate brake hydraulic system. If hydraulic pressure in systems 4 and 1 are low,
system 2 powers the alternate brake system.
Loss of hydraulic systems 4, 1, and 2 causes the brake source light to illuminate.

Since there is no working "parking brake source light" it is simulated by the parking brake lever not latching if hydraulic pressure is low

brake pressure can be viewed on the gauge just behind the pilot yolk, needs at least 1000psi for the brakes to function, top left of this picture
![image](https://user-images.githubusercontent.com/6773686/84441851-ccab1200-ac3c-11ea-9a4b-2496d803c517.png)

**Comment by mSparks43** [comment]
Should be resolved by https://github.com/YesAviation/747-400/commit/8b6ab42ef233aa9d03de65615cc90ffd5f16d8a2
