### ISSUE TITLE
Better Pushback and parking brakes

### ISSUE THREAD

**Issue by skmcconnell361** [YesAviation/747-400#9]
Better Pushback is not recognizing parking status, it tells me to release the parking breaks. and will not connect.

**Comment by Rubenzxl** [comment]
Same problem here

**Comment by mSparks43** [comment]
sim/flightmodel/controls/parkbrake is operating over the full range 0-1, if someone can let me know how else they are reading parking status I can add it.

**Comment by airfightergr** [comment]
Try this `sim/cockpit2/controls/parking_brake_ratio`

**Comment by mSparks43** [comment]
->sim/cockpit2/controls/parking_brake_ratio
full range there too.
sim/cockpit2/controls/left_brake_ratio
sim/cockpit2/controls/right_brake_ratio
always 0.

**Comment by mSparks43** [comment]
Sometime after my Dec 3rd commit it looks like the cockpit has been broken, this is probably the cause of issues #11 and #13 can someone experiencing these please checkout that tree and see if this is the case.

**Comment by mSparks43** [comment]
This issue seems to have been an issue caused by a lack of hydraulic pressure, please ensure you have at least engine 4 aux engaged for hydraulic pressure to drive the brake pressure, "alternate brake source" isn't supported.
closing this issue as resolved, if it persists please reopen, open a different issue for any related problems
